export type CollectionSourceSeed = {
  name: string
  slug: string
  type: string
  target: 'news' | 'github' | 'skill' | 'prompt'
  url?: string
  enabled?: boolean
  priority?: number
  language?: string
  region?: string
  category?: string
  frequencyMins?: number
  config?: Record<string, unknown>
}

const newsSource = (
  name: string,
  slug: string,
  url: string,
  category: string,
  priority: number,
  language = 'en',
  region = 'global',
  limit = 30,
  extraConfig: Record<string, unknown> = {},
): CollectionSourceSeed => ({
  name,
  slug,
  type: 'RSS',
  target: 'news',
  url,
  language,
  region,
  category,
  priority,
  frequencyMins: 360,
  config: { limit, timeoutMs: 45000, ...extraConfig },
})

const githubSource = (
  name: string,
  slug: string,
  query: string,
  category: string,
  priority: number,
): CollectionSourceSeed => ({
  name,
  slug,
  type: 'GitHub API',
  target: 'github',
  language: 'multi',
  region: 'global',
  category,
  priority,
  frequencyMins: 1440,
  config: {
    query,
    direction: category,
    perPage: 100,
  },
})

const githubSkillIndexSource = (
  name: string,
  slug: string,
  category: string,
  priority: number,
  codeQueries: string[],
  extraConfig: Record<string, unknown> = {},
): CollectionSourceSeed => ({
  name,
  slug,
  type: 'GitHub Skill Index',
  target: 'skill',
  language: 'multi',
  region: 'global',
  category,
  priority,
  frequencyMins: 360,
  config: {
    indexStateFile: `.collector-state/${slug}.json`,
    queryBatchSize: 1,
    pageLimitPerQuery: 1,
    perPage: 20,
    maxTotal: 30,
    rawFetchTimeoutMs: 4000,
    maxRawFetches: 20,
    repoSearchLimit: 12,
    fallbackMaxRepos: 8,
    fallbackLimitPerRepo: 30,
    allowRepoFallback: false,
    codeQueries,
    repoQueries: [],
    ...extraConfig,
  },
})

const promptSource = (
  name: string,
  slug: string,
  url: string,
  category: string,
  priority: number,
  language = 'zh',
  region = 'cn',
  limit = 60,
  extraConfig: Record<string, unknown> = {},
): CollectionSourceSeed => ({
  name,
  slug,
  type: 'Prompt Site',
  target: 'prompt',
  url,
  language,
  region,
  category,
  priority,
  frequencyMins: 720,
  config: { limit, timeoutMs: 45000, ...extraConfig },
})

const aiNewsSources: CollectionSourceSeed[] = [
  newsSource('OpenAI News', 'ai-news-openai-rss', 'https://openai.com/news/rss.xml', '模型动态', 100, 'en', 'global', 25, { timeoutMs: 60000 }),
  newsSource('Google AI Blog', 'ai-news-google-ai-rss', 'https://blog.google/technology/ai/rss/', '模型动态', 96, 'en', 'global', 25),
  newsSource('Hugging Face Blog', 'ai-news-huggingface-rss', 'https://huggingface.co/blog/feed.xml', '开源模型与工具', 95, 'en', 'global', 12, { timeoutMs: 60000 }),
  newsSource('Last Week in AI', 'ai-news-lastweekinai-rss', 'https://lastweekin.ai/feed', '行业新闻', 94, 'en', 'global', 30, { timeoutMs: 60000 }),
  newsSource('The Gradient', 'ai-news-thegradient-rss', 'https://thegradient.pub/rss/', '技术文章', 93, 'en', 'global', 25, { timeoutMs: 60000 }),
  newsSource('Ahead of AI', 'ai-news-aheadofai-rss', 'https://magazine.sebastianraschka.com/feed', '技术文章', 92, 'en', 'global', 25, { timeoutMs: 60000 }),
  newsSource('MIT Technology Review AI', 'ai-news-mittr-rss', 'https://www.technologyreview.com/topic/artificial-intelligence/feed/', '行业新闻', 91, 'en', 'global', 25),
  newsSource('MarkTechPost AI', 'ai-news-marktechpost-rss', 'https://www.marktechpost.com/feed/', '研究进展', 90, 'en', 'global', 30),
  newsSource('TechCrunch AI', 'ai-news-techcrunch-rss', 'https://techcrunch.com/category/artificial-intelligence/feed/', '行业新闻', 88, 'en', 'global', 25),
  newsSource('BAIR Blog', 'ai-news-bair-rss', 'https://bair.berkeley.edu/blog/feed.xml', '研究进展', 87, 'en', 'global', 20),
  newsSource('The Verge AI', 'ai-news-theverge-rss', 'https://www.theverge.com/rss/ai-artificial-intelligence/index.xml', '产品更新', 84, 'en', 'global', 25),
  newsSource('Ars Technica AI', 'ai-news-arstechnica-rss', 'https://arstechnica.com/tag/artificial-intelligence/feed/', '行业新闻', 83, 'en', 'global', 20),
  newsSource('arXiv cs.AI', 'ai-news-arxiv-cs-ai-rss', 'https://export.arxiv.org/rss/cs.AI', '研究进展', 82, 'en', 'global', 20),
  newsSource('arXiv cs.CL', 'ai-news-arxiv-cs-cl-rss', 'https://export.arxiv.org/rss/cs.CL', '研究进展', 81, 'en', 'global', 20),
  newsSource('arXiv cs.LG', 'ai-news-arxiv-cs-lg-rss', 'https://export.arxiv.org/rss/cs.LG', '研究进展', 80, 'en', 'global', 20),
  newsSource('arXiv cs.CV', 'ai-news-arxiv-cs-cv-rss', 'https://export.arxiv.org/rss/cs.CV', '研究进展', 79, 'en', 'global', 20),
  newsSource('量子位', 'ai-news-qbitai-rss', 'https://www.qbitai.com/rss', '国内 AI 资讯', 86, 'zh', 'cn', 25),
  newsSource('机器之心', 'ai-news-jiqizhixin-rss', 'https://www.jiqizhixin.com/rss', '国内 AI 资讯', 85, 'zh', 'cn', 25, { lenientXml: true }),
]

const promptSources: CollectionSourceSeed[] = [
  promptSource('AiShort 社区提示词', 'prompt-aishort-community', 'https://www.aishort.top/community-prompts', '各行业提示词库', 92, 'zh', 'cn', 80, {
    parser: 'aishort-community-prompts',
    apiBase: 'https://api.newzone.top/api',
    stateFile: '.collector-state/aishort-prompts.json',
    pageSize: 50,
    maxTotal: 800,
    maxPagesPerMode: 10,
    queryMaxPages: 2,
    requestDelayMs: 250,
    bulkSize: 50,
    sorts: [
      { field: 'id', order: 'desc' },
      { field: 'upvoteDifference', order: 'desc' },
      { field: 'updatedAt', order: 'desc' },
    ],
    queries: [
      '营销',
      '写作',
      '设计',
      '编程',
      '教育',
      '法律',
      '金融',
      '电商',
      '客服',
      '视频',
      '数据',
      '产品',
      '运营',
      '小红书',
      '抖音',
      '简历',
      '论文',
      'SQL',
      'Python',
      'PPT',
      'Excel',
    ],
  }),
]

export const manualSkillItems = [
  {
    name: '网页搜索与检索',
    description: '根据问题拆解检索词，调用搜索引擎、站内搜索或指定站点，返回可验证链接、摘要和引用线索。',
    category: 'Research',
    tags: ['搜索', '检索', '资料核验'],
  },
  {
    name: '多来源热点聚类',
    description: '把多个资讯源、RSS、社媒线索和项目更新合并成热点主题，输出时间线、代表链接和运营推荐角度。',
    category: 'News',
    tags: ['热点', '资讯', '聚类'],
  },
  {
    name: '长文中文摘要',
    description: '把论文、报告、博客、访谈或产品文档压缩成中文摘要、关键结论、风险点和适合人群。',
    category: 'Content',
    tags: ['摘要', '中文化', '长文处理'],
  },
  {
    name: '内容改写与分发',
    description: '把同一份原始材料改写成公众号、短视频脚本、社群帖、邮件和产品更新说明。',
    category: 'Content',
    tags: ['改写', '分发', '运营内容'],
  },
  {
    name: '标题与选题生成',
    description: '围绕目标受众和平台风格生成标题组、选题角度、亮点提炼和点击风险提示。',
    category: 'Content',
    tags: ['标题', '选题', '增长'],
  },
  {
    name: 'GitHub 项目解析',
    description: '解析仓库 README、Topic、Star、最近更新和代码结构，说明项目是什么、解决什么问题、适合谁用。',
    category: 'GitHub',
    tags: ['GitHub', '开源项目', '项目解读'],
  },
  {
    name: 'GitHub Top 100 榜单解释',
    description: '按 Agent、RAG、LLM 应用、模型服务、AI 编程和自动化方向生成可解释榜单与上榜理由。',
    category: 'GitHub',
    tags: ['榜单', 'Top100', '开源趋势'],
  },
  {
    name: '文件解析与结构化',
    description: '从 PDF、Word、PPT、表格、Markdown 或网页中提取标题、表格、段落和字段，转成结构化数据。',
    category: 'Data',
    tags: ['文件解析', '结构化', '抽取'],
  },
  {
    name: '知识库检索问答',
    description: '基于文档库、FAQ 或项目资料进行带引用问答，输出答案、证据片段和缺口问题。',
    category: 'RAG',
    tags: ['RAG', '知识库', '问答'],
  },
  {
    name: 'API 调用与工具接入',
    description: '把外部 API 能力封装成 Agent 可调用工具，定义参数、鉴权、错误处理和返回结构。',
    category: 'Engineering',
    tags: ['API', '工具调用', '集成'],
  },
  {
    name: '工作流自动化编排',
    description: '把采集、清洗、模型处理、审核、通知和发布串成可复用工作流，并保留失败重试策略。',
    category: 'Automation',
    tags: ['工作流', '自动化', '任务编排'],
  },
  {
    name: '浏览器自动化采集',
    description: '对公开页面执行列表页采集、详情页抽取、分页跟随和基础反失败处理，遵守来源合规边界。',
    category: 'Automation',
    tags: ['浏览器', '采集', 'Scrapling'],
  },
  {
    name: '代码仓库分析',
    description: '读取项目目录、依赖、脚本和核心模块，输出架构说明、风险点、运行方式和二次开发建议。',
    category: 'Engineering',
    tags: ['代码分析', '仓库理解', '工程'],
  },
  {
    name: '需求到任务拆解',
    description: '把业务目标拆成里程碑、数据模型、接口、后台任务、测试点和上线检查清单。',
    category: 'Planning',
    tags: ['PRD', '任务拆解', '项目管理'],
  },
  {
    name: 'Prompt 评测集生成',
    description: '为 Prompt、Agent 或 RAG 系统生成覆盖正常、边界、失败和安全场景的评测用例。',
    category: 'Evaluation',
    tags: ['Prompt', '评测', '质量控制'],
  },
  {
    name: 'RAG 数据清洗',
    description: '对知识库资料进行去噪、切片、元数据补齐、重复内容合并和低质量片段标记。',
    category: 'RAG',
    tags: ['RAG', '数据清洗', '切片'],
  },
  {
    name: 'Agent 模板生成',
    description: '根据业务场景生成 Agent 角色、目标、工具权限、执行流程、失败兜底和评测项。',
    category: 'Agent',
    tags: ['Agent', '模板', '角色设计'],
  },
  {
    name: 'MCP 工具设计',
    description: '为数据库、内部系统或第三方服务设计 MCP server 的资源、工具、权限和测试方案。',
    category: 'Engineering',
    tags: ['MCP', '工具协议', 'Agent'],
  },
  {
    name: '社交媒体写作',
    description: '把产品动态、技术文章或热点事件改写成适合 X、即刻、小红书、公众号和社群的内容。',
    category: 'Content',
    tags: ['社媒', '文案', '传播'],
  },
  {
    name: '论文速读与复现线索',
    description: '抽取论文问题、方法、实验、数据集、代码链接、局限和可复现步骤。',
    category: 'Research',
    tags: ['论文', '研究', '复现'],
  },
  {
    name: '产品发布解读',
    description: '把模型发布、工具更新或平台公告整理成中文亮点、影响范围、适合用户和迁移建议。',
    category: 'News',
    tags: ['产品发布', '模型动态', '解读'],
  },
  {
    name: '竞品对比矩阵',
    description: '围绕功能、价格、开源情况、部署方式、集成能力和风险生成竞品对比表。',
    category: 'Research',
    tags: ['竞品', '对比', '产品分析'],
  },
  {
    name: '数据表清洗分析',
    description: '清洗 CSV、Excel 或数据库导出数据，生成字段说明、异常检查、统计摘要和图表建议。',
    category: 'Data',
    tags: ['表格', '数据清洗', '分析'],
  },
  {
    name: '会议纪要行动项',
    description: '把会议记录转成议题摘要、决策、待办、负责人、截止时间和风险提醒。',
    category: 'Operations',
    tags: ['会议纪要', '行动项', '运营'],
  },
  {
    name: '客服知识库回复',
    description: '基于产品文档和 FAQ 生成客服回复、追问问题、引用依据和人工转接条件。',
    category: 'RAG',
    tags: ['客服', '知识库', '问答'],
  },
  {
    name: '安全合规检查',
    description: '检查候选内容、工具或数据源是否存在版权、隐私、登录绕过、付费墙和敏感信息风险。',
    category: 'Governance',
    tags: ['合规', '安全', '审核'],
  },
  {
    name: '运营审核与标签治理',
    description: '为候选内容生成分类、标签、推荐理由、低质原因和合并建议，辅助运营审核发布。',
    category: 'Operations',
    tags: ['审核', '标签', '治理'],
  },
  {
    name: '图片视频脚本生成',
    description: '围绕资讯、课程或项目生成封面提示词、分镜脚本、字幕要点和素材清单。',
    category: 'Creative',
    tags: ['图片', '视频', '脚本'],
  },
  {
    name: '用户画像与场景分析',
    description: '根据社区用户、工具能力和使用行为生成用户画像、需求场景、推荐话术和转化路径。',
    category: 'Research',
    tags: ['用户画像', '场景', '推荐'],
  },
  {
    name: '错误日志诊断',
    description: '分析运行日志、错误堆栈和接口返回，定位可能原因、复现路径和修复建议。',
    category: 'Engineering',
    tags: ['日志', '诊断', '排错'],
  },
  {
    name: '数据源质量评分',
    description: '根据来源可信度、更新频率、内容完整度、重复率和历史失败率给采集源打分。',
    category: 'Governance',
    tags: ['数据源', '评分', '监控'],
  },
  {
    name: 'Skill 候选抽取',
    description: '从项目 README、模板说明、案例和运营录入中抽取可复用能力名称、触发场景和输入输出。',
    category: 'Skill',
    tags: ['Skill', '抽取', '能力沉淀'],
  },
  {
    name: 'Agent 工具权限设计',
    description: '为 Agent 设计可调用工具、权限边界、确认步骤、审计日志和失败兜底策略。',
    category: 'Agent',
    tags: ['权限', '工具', 'Agent'],
  },
  {
    name: '多语言本地化',
    description: '把英文资讯、README 或产品文档本地化为中文，并保留术语表、上下文和不确定项。',
    category: 'Content',
    tags: ['翻译', '本地化', '术语'],
  },
  {
    name: '课程学习路径生成',
    description: '根据主题、水平和目标产出生成学习路线、资料顺序、练习任务和验收标准。',
    category: 'Education',
    tags: ['课程', '学习路径', '训练营'],
  },
  {
    name: '提示词改写优化',
    description: '把原始提示词改写成目标明确、上下文完整、输出格式稳定、边界条件清晰的版本。',
    category: 'Prompt',
    tags: ['Prompt', '改写', '稳定输出'],
  },
]

export const defaultCollectionSources: CollectionSourceSeed[] = [
  ...aiNewsSources,
  ...promptSources,

  githubSource('GitHub Agent Frameworks', 'github-agent-frameworks', 'topic:ai-agent stars:>100', 'Agent', 98),
  githubSource('GitHub Agent Systems', 'github-agent-systems', 'topic:agents stars:>100', 'Agent', 96),
  githubSource('GitHub RAG Projects', 'github-rag-projects', 'topic:rag stars:>100', 'RAG', 95),
  githubSource('GitHub Vector AI Projects', 'github-vector-ai-projects', 'topic:vector-database stars:>100', 'RAG', 90),
  githubSource('GitHub LLM App Projects', 'github-llm-app-projects', 'topic:llm stars:>500', 'LLM 应用', 94),
  githubSource('GitHub Chatbot Projects', 'github-chatbot-projects', 'topic:chatbot stars:>500', 'LLM 应用', 88),
  githubSource('GitHub Model Serving Projects', 'github-model-serving-projects', 'topic:llm-serving stars:>50', '模型服务', 90),
  githubSource('GitHub Local LLM Projects', 'github-local-llm-projects', 'topic:local-llm stars:>100', '模型服务', 86),
  githubSource('GitHub AI Coding Projects', 'github-ai-coding-projects', 'topic:ai-coding stars:>50', 'AI 编程工具', 90),
  githubSource('GitHub Code Generation Projects', 'github-code-generation-projects', 'topic:code-generation stars:>100', 'AI 编程工具', 84),
  githubSource('GitHub Automation AI Projects', 'github-automation-ai-projects', 'topic:automation topic:ai stars:>100', '自动化', 84),
  githubSource('GitHub MCP Projects', 'github-mcp-projects', 'mcp ai stars:>50', 'Agent 工具生态', 82),

  {
    name: 'skills.sh All Skills',
    slug: 'skills-sh-all',
    type: 'Skills.sh API',
    target: 'skill',
    url: 'https://www.skills.sh',
    language: 'multi',
    region: 'global',
    category: '外部 Skill 市场',
    priority: 100,
    frequencyMins: 1440,
    config: {
      totalExpected: 847156,
      apiBase: 'https://www.skills.sh/api/v1',
      listEndpoint: '/skills',
      detailEndpoint: '/skills/{id}',
      pageParam: 'page',
      pageSizeParam: 'limit',
      pageStart: 1,
      pageSize: 100,
      maxTotal: 847156,
      publicFallback: true,
      publicPageLimit: 250,
      publicMaxTotal: 9590,
      detailEnrichLimit: 0,
      nativePublicFetch: true,
      publicFetchTimeoutMs: 45000,
      publicPages: [
        'https://www.skills.sh/',
        'https://www.skills.sh/trending',
        'https://www.skills.sh/hot',
        'https://www.skills.sh/official',
        'https://www.skills.sh/topic/react',
        'https://www.skills.sh/topic/nextjs',
        'https://www.skills.sh/topic/design',
        'https://www.skills.sh/topic/mobile',
        'https://www.skills.sh/topic/agent-workflows',
        'https://www.skills.sh/topic/databases',
        'https://www.skills.sh/topic/testing',
        'https://www.skills.sh/topic/marketing',
      ],
      authEnv: 'SKILLS_SH_TOKEN',
      authType: 'bearer',
      requiresAuth: true,
    },
  },
  {
    name: 'skills.sh Browser Slow Crawl',
    slug: 'skills-sh-browser-slow',
    type: 'Skills.sh Browser',
    target: 'skill',
    url: 'https://www.skills.sh',
    language: 'multi',
    region: 'global',
    category: '外部 Skill 市场',
    priority: 99,
    frequencyMins: 720,
    config: {
      mode: 'dynamic-browser-slow',
      totalTarget: 80000,
      browserLimit: 80,
      scrollSteps: 10,
      delayMs: 1000,
      maxClicks: 20,
      clickDelayMs: 700,
      discoverPageLimit: 800,
      stateFile: '.collector-state/skills-sh-browser.json',
      clickLoadMore: true,
      includeSeen: true,
      browserPages: [
        'https://www.skills.sh/',
        'https://www.skills.sh/trending',
        'https://www.skills.sh/hot',
        'https://www.skills.sh/official',
        'https://www.skills.sh/topic/react',
        'https://www.skills.sh/topic/nextjs',
        'https://www.skills.sh/topic/design',
        'https://www.skills.sh/topic/mobile',
        'https://www.skills.sh/topic/agent-workflows',
        'https://www.skills.sh/topic/databases',
        'https://www.skills.sh/topic/testing',
        'https://www.skills.sh/topic/marketing',
      ],
    },
  },
  {
    name: 'skills.sh Public Search Index',
    slug: 'skills-sh-search-index',
    type: 'Skills.sh Search API',
    target: 'skill',
    url: 'https://www.skills.sh',
    language: 'multi',
    region: 'global',
    category: '外部 Skill 市场',
    priority: 99,
    frequencyMins: 360,
    config: {
      endpoint: 'https://www.skills.sh/api/search',
      stateFile: '.collector-state/skills-sh-search-index.json',
      queryBatchSize: 18,
      perQueryLimit: 300,
      maxTotal: 5000,
      delayMs: 1300,
      retryDelayMs: 15000,
      queries: [
        'skill', 'agent', 'github', 'code', 'design', 'image', 'video', 'data', 'python', 'next',
        'claude', 'mcp', 'pdf', 'react', 'web', 'api', 'llm', 'rag', 'chat', 'browser',
        'content', 'vue', 'go', 'golang', 'excel', 'slides', 'docs', 'gmail', 'calendar', 'figma',
        'vercel', 'google', 'gws', 'baoyu', 'marketing', 'gsap', 'azure', 'amazon', 'swiftui', 'cloudflare',
        'seo', 'workflow', 'test', 'database', 'automation', 'typescript', 'javascript', 'node', 'frontend', 'backend',
        'mobile', 'ios', 'android', 'swift', 'kotlin', 'sql', 'postgres', 'supabase', 'firebase', 'docker',
        'kubernetes', 'security', 'audit', 'research', 'search', 'writing', 'copywriting', 'email', 'social', 'crm',
        'sales', 'analytics', 'chart', 'spreadsheet', 'presentation', 'document', 'notion', 'slack', 'discord', 'linear',
        'jira', 'openai', 'anthropic', 'gemini', 'cursor', 'codex', 'copilot', 'windsurf', 'cline', 'browser-use',
        'firecrawl', 'scraping', 'crawler', 'knowledge', 'retrieval', 'vector', 'embedding', 'audio', 'music', 'speech',
        'video-edit', 'image-edit', 'generate', 'testing', 'playwright', 'storybook', 'tailwind', 'nextjs', 'remix', 'svelte',
      ],
    },
  },
  {
    name: 'skills.sh GitHub Source Expansion',
    slug: 'skills-sh-github-sources',
    type: 'Skills.sh GitHub Sources',
    target: 'skill',
    url: 'https://www.skills.sh',
    language: 'multi',
    region: 'global',
    category: 'skills.sh GitHub 源',
    priority: 98,
    frequencyMins: 720,
    config: {
      sourceStateFile: '.collector-state/skills-sh-browser.json',
      useCollectedSources: true,
      sourceHintLimit: 50000,
      githubStateFile: '.collector-state/skills-sh-github-sources.json',
      repoBatchSize: 2,
      maxRepos: 120,
      maxTotal: 80,
      limitPerRepo: 40,
      hintLimitPerRepo: 60,
      includePluginDirs: false,
      repos: ['anthropics/skills'],
    },
  },
  {
    name: 'GitHub Global Skill Index',
    slug: 'github-global-skill-index',
    type: 'GitHub Skill Index',
    target: 'skill',
    language: 'multi',
    region: 'global',
    category: 'GitHub 全网 Skill 索引',
    priority: 97,
    frequencyMins: 360,
    config: {
      indexStateFile: '.collector-state/github-skill-index.json',
      queryBatchSize: 2,
      pageLimitPerQuery: 1,
      perPage: 30,
      maxTotal: 120,
      repoSearchLimit: 10,
      fallbackMaxRepos: 8,
      fallbackLimitPerRepo: 30,
      allowRepoFallback: false,
      codeQueries: [
        'filename:SKILL.md',
        'path:skills filename:SKILL.md',
        'path:agent-skills filename:SKILL.md',
        'path:.agents filename:SKILL.md',
        'path:.codex filename:SKILL.md',
        'path:.skills filename:SKILL.md',
        'path:claude-skills filename:SKILL.md',
        'path:codex-skills filename:SKILL.md',
        'path:skills "SKILL.md"',
        'path:skills "description:"',
        '"name:" "description:" filename:SKILL.md',
        '"Claude Code" "SKILL.md"',
        '"agent skill" filename:SKILL.md',
        '"claude skills" "SKILL.md"',
        '"codex skills" "SKILL.md"',
        '"awesome skills" "agent"',
      ],
      repoQueries: [],
    },
  },
  githubSkillIndexSource(
    'GitHub Scrapling-style Crawler Skills',
    'github-python-crawler-skill-index',
    'Scrapling 风格爬虫采集 Skill',
    96,
    [
      'filename:SKILL.md scrapling',
      '"Scrapling" "SKILL.md"',
      '"D4Vinci/Scrapling" "SKILL.md"',
      '"adaptive scraping" "SKILL.md"',
      '"stealth scraping" "SKILL.md"',
      '"browser automation" "scraping" filename:SKILL.md',
      '"Playwright" "scraping" filename:SKILL.md',
      '"Playwright" "crawler" filename:SKILL.md',
      '"Scrapy" "spider" filename:SKILL.md',
      '"Scrapy" "crawler" filename:SKILL.md',
      '"Firecrawl" "SKILL.md"',
      '"crawl4ai" "SKILL.md"',
      'filename:SKILL.md web scraping scrapy',
      'filename:SKILL.md web scraping playwright',
      'filename:SKILL.md selenium scraping',
      'filename:SKILL.md beautifulsoup scraping',
      'filename:SKILL.md bs4 scraping',
      'filename:SKILL.md lxml scraping',
      'filename:SKILL.md parsel scrapy',
      'path:skills filename:SKILL.md web scraping',
      'path:skills filename:SKILL.md browser automation scraping',
    ],
    {
      queryBatchSize: 1,
      pageLimitPerQuery: 1,
      perPage: 20,
      maxTotal: 30,
      rawFetchTimeoutMs: 4000,
      maxRawFetches: 20,
      minTopicKeywordMatches: 1,
      topicKeywords: [
        'scrapling',
        'D4Vinci/Scrapling',
        'scrapy',
        'playwright',
        'selenium',
        'beautifulsoup',
        'bs4',
        'lxml',
        'parsel',
        'xpath',
        'css selector',
        'httpx',
        'aiohttp',
        'firecrawl',
        'crawl4ai',
        'web scraping',
        'stealth scraping',
        'adaptive scraping',
        'anti bot',
        'anti-bot',
        'proxy rotation',
        'spider',
        'scraper',
        'data extraction',
        'browser automation',
        '爬虫',
        '采集',
        '抓取',
      ],
      allowRepoFallback: true,
      repoSearchLimit: 8,
      fallbackMaxRepos: 5,
      fallbackLimitPerRepo: 20,
      repoQueries: [
        'scrapling web scraping stars:>5',
        'scrapy spider web scraping stars:>5',
        'playwright scraping python stars:>5',
        'selenium scraping python stars:>5',
        'beautifulsoup web scraping python stars:>5',
        'firecrawl crawler skills stars:>5',
        'crawl4ai crawler skills stars:>5',
      ],
    },
  ),
  githubSkillIndexSource(
    'GitHub Shannon Hacker Skills',
    'github-cybersecurity-skill-index',
    'Shannon 黑客技能库 Skill',
    95,
    [
      '"Shannon" "SKILL.md"',
      '"KeygraphHQ/shannon" "SKILL.md"',
      '"unicodeveloper/shannon" "SKILL.md"',
      '"Shannon" "pentest" "SKILL.md"',
      '"hacker skills" "SKILL.md"',
      '"offensive security" "SKILL.md"',
      '"AI pentester" "SKILL.md"',
      '"web exploitation" "SKILL.md"',
      '"red team" "SKILL.md"',
      '"blue team" "SKILL.md"',
      '"ctf" "SKILL.md"',
      '"pwn" "SKILL.md"',
      '"reverse engineering" "SKILL.md"',
      '"malware analysis" "SKILL.md"',
      'filename:SKILL.md osint',
      'filename:SKILL.md pentest',
      'filename:SKILL.md penetration testing',
      'filename:SKILL.md web exploitation',
      'filename:SKILL.md shannon',
      'filename:SKILL.md red team',
      'filename:SKILL.md blue team',
      'path:skills filename:SKILL.md offensive security',
      'path:skills filename:SKILL.md red team',
      'path:skills filename:SKILL.md osint',
      '"OWASP" "SKILL.md"',
    ],
    {
      queryBatchSize: 1,
      pageLimitPerQuery: 1,
      perPage: 20,
      maxTotal: 30,
      rawFetchTimeoutMs: 4000,
      maxRawFetches: 20,
      minTopicKeywordMatches: 1,
      topicKeywords: [
        'shannon',
        'KeygraphHQ/shannon',
        'unicodeveloper/shannon',
        'hacker',
        'hacker skills',
        'AI pentester',
        'offensive security',
        'pentest',
        'penetration testing',
        'web exploitation',
        'red team',
        'blue team',
        'ctf',
        'pwn',
        'reverse engineering',
        'reversing',
        'forensics',
        'malware analysis',
        'osint',
        'bug bounty',
        'burp',
        'nmap',
        'metasploit',
        'kali',
        'owasp',
        'appsec',
        'vulnerability',
        'exploit',
        'bug hunter',
        'bug-hunter',
        'bug hunting',
        'vuln hunting',
        'web-vuln',
        'credential attack',
        'password spray',
        'security vulnerabilities',
        'secure code',
        'secure web applications',
        'sast',
        'semgrep',
        'yara',
        'sigma',
        '安全',
        '渗透',
        '漏洞',
        '攻防',
        '审计',
      ],
      allowRepoFallback: true,
      repoSearchLimit: 8,
      fallbackMaxRepos: 5,
      fallbackLimitPerRepo: 20,
      repoQueries: [
        'Shannon hacker skills stars:>5',
        'AI pentester skills stars:>5',
        'offensive security skills stars:>5',
        'red team skills stars:>5',
        'web exploitation skills stars:>5',
        'osint skills stars:>5',
        'ctf pwn reverse engineering skills stars:>5',
      ],
    },
  ),
]

export const deprecatedCollectionSourceSlugs = [
  'codex-local-skills',
  'openai-news-rss',
  'anthropic-news-rss',
  'anthropic-research-rss',
  'google-deepmind-rss',
  'google-ai-blog-rss',
  'huggingface-blog-rss',
  'huggingface-papers-rss',
  'arxiv-cs-ai-rss',
  'arxiv-cs-cl-rss',
  'arxiv-cs-lg-rss',
  'arxiv-cs-cv-rss',
  'techcrunch-ai-rss',
  'venturebeat-ai-rss',
  'theverge-ai-rss',
  'marktechpost-rss',
  'the-decoder-rss',
  'qbitai-rss',
  'jiqizhixin-rss',
  'aibase-rss',
  'project-agent-skills',
  'public-agent-skill-repos',
  'lobehub-skills',
  'dify-marketplace-templates',
  'n8n-workflow-templates',
  'langchain-hub',
  'manual-skill-seeds',
  'producthunt-ai-listing',
]
